[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.140.2"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production.environment]
  HUGO_ENV = "production"
 